# This is a config for Moru sandbox template.
# You can use template ID or template name (base) to create a sandbox:

# Python SDK
# from moru import Sandbox, AsyncSandbox
# sandbox = Sandbox("base") # Sync sandbox
# sandbox = await AsyncSandbox.create("base") # Async sandbox

# JS SDK
# import { Sandbox } from '@moru-ai/core'
# const sandbox = await Sandbox.create('base')

team_id = "79d0b373-31b1-4185-b633-67ddb67bc0f9"
memory_mb = 512
cpu_count = 1
dockerfile = "moru.Dockerfile"
template_name = "base"
template_id = "32u2qcnygu3zemwfe3rb"
