# This is a config for Moru sandbox template.
# You can use template ID or template name (base) to create a sandbox:

# Python SDK
# from moru import Sandbox, AsyncSandbox
# sandbox = Sandbox("base") # Sync sandbox
# sandbox = await AsyncSandbox.create("base") # Async sandbox

# JS SDK
# import { Sandbox } from '@moru-ai/core'
# const sandbox = await Sandbox.create('base')

team_id = "460355b3-4f64-48f9-9a16-4442817f79f5"
memory_mb = 512
dockerfile = "moru.Dockerfile"
template_name = "base"
template_id = "rki5dems9wqfm4r03t7g"
